return {
  {
    'catppuccin/nvim',
    lazy = false,
    name = 'catppuccin',
    priority = 1000,
    opts = {
      integrations = {
        aerial = true,
        alpha = true,
        cmp = true,
        dashboard = true,
        flash = true,
        grug_far = true,
        gitsigns = true,
        headlines = true,
        illuminate = true,
        indent_blankline = { enabled = true },
        leap = true,
        lsp_trouble = true,
        mason = true,
        markdown = true,
        mini = true,
        native_lsp = {
          enabled = true,
          underlines = {
            errors = { 'undercurl' },
            hints = { 'undercurl' },
            warnings = { 'undercurl' },
            information = { 'undercurl' },
          },
        },
        navic = { enabled = true, custom_bg = 'lualine' },
        neotest = true,
        neotree = true,
        noice = true,
        notify = true,
        semantic_tokens = true,
        telescope = true,
        treesitter = true,
        treesitter_context = true,
        which_key = true,
      },
      -- color_overrides = {
      --   latte = {
      --     rosewater = '#cc7983',
      --     flamingo = '#bb5d60',
      --     pink = '#d54597',
      --     mauve = '#a65fd5',
      --     red = '#b7242f',
      --     maroon = '#db3e68',
      --     peach = '#e46f2a',
      --     yellow = '#bc8705',
      --     green = '#1a8e32',
      --     teal = '#00a390',
      --     sky = '#089ec0',
      --     sapphire = '#0ea0a0',
      --     blue = '#017bca',
      --     lavender = '#8584f7',
      --     text = '#444444',
      --     subtext1 = '#555555',
      --     subtext0 = '#666666',
      --     overlay2 = '#777777',
      --     overlay1 = '#888888',
      --     overlay0 = '#999999',
      --     surface2 = '#aaaaaa',
      --     surface1 = '#bbbbbb',
      --     surface0 = '#cccccc',
      --     base = '#ffffff',
      --     mantle = '#eeeeee',
      --     crust = '#dddddd',
      --   },
      -- },
    },
    config = function(_, opts)
      require('catppuccin').setup(opts)
      vim.cmd.colorscheme 'catppuccin-latte'
      -- You can configure highlights by doing something like:
      vim.cmd.hi 'Comment gui=none'
    end,
  },
}
