return {}
-- return {
--   {
--     'sigmaSd/deno-nvim',
--     dependencies = { 'nvim-lua/plenary.nvim' },
--     config = function()
--       require('deno-nvim').setup {
--         server = {
--           cmd = { 'deno', 'lsp' },
--           root_dir = require('lspconfig.util').root_pattern('deno.json', 'deno.jsonc'),
--           filetypes = { 'typescript', 'typescriptreact', 'javascript', 'javascriptreact' },
--           init_options = {
--             lint = true,
--             unstable = true,
--           },
--         },
--       }
--     end,
--   },
-- }
